### ISSUE TITLE
calling `register-collecting-blit` leaves a blit around on macOS

### ISSUE THREAD

**Issue by florence** [racket/gui#94] opened 2018-02-01 21:18 UTC
It looks like each call to "register-collecting-blit" causes one permanent blit to appear. This blit acts a separate tiny window in expose mode, even after the blit is unregistered.

Example program:
```
#lang racket/gui
(define f (new frame% [label ""]))
(define hp (new horizontal-panel% [parent f]))
(define c (new canvas% [parent hp]))
(define on (make-bitmap 20 20))
(define off (make-bitmap 20 20))
(send c min-width 20)
(send c min-height 20)
(define bdc (make-object bitmap-dc% on))
(send bdc set-smoothing 'smoothed)
(send bdc clear)
(send bdc set-bitmap off)
(send bdc set-smoothing 'smoothed)
(send bdc set-brush "black" 'solid)
(send bdc set-pen "black" 0 'transparent)
(send bdc draw-ellipse 0 0 20 20)
(send bdc set-bitmap #f)

(register-collecting-blit c 0 0 20 20 on off)
(send f show #t)

(for ([i (in-range 4)])
  (unregister-collecting-blit c)
  (register-collecting-blit c 0 0 20 20 on off))
```

This causes 5 new blit "windows" to appear, sometimes with the on bitmap, sometimes with the off bitmap.

This has been causing a bit of a problem w/ DrRacket because each new window creates a new blit. After a while all the extra blits cause a noticeable slow down in expose mode.

I'm on macOS 10.13.2, and Racket v6.12.0.3.

**Comment by jbclements** [comment] 2018-02-01 21:27
Yes! I believe this is the same issue that I reported in my Dec. 20 message to racket-users, when I wrote:

> Looks to me like DrR is leaking… windows.

> 
> Specifically:
> 
> On up-to-date DrR (just rebuilt from repo, version 6.11.0.5--2017-12-20), pretty much up-to-date OS X (10.13.1 (17B1003)), I notice something very strange. I’ve seen it on two computers, so I think it should be reproducible on any computer:
> 
> 1) Open a DrR Window, nice and big.
> 2) Grab the right edge of the window, and slowly drag it to the left, shrinking the window horizontally. Watch the area of the GC box.
> 3) You should see a little trail of white left behind the lower right corner of the window.
> 4) After about 1.5 seconds of slowly dragging, let go.
> 5) The trail is still there. What is it?
> 6) to find out, use a three-finger upward wipe; this separates all of the windows on the screen, so you can see them separately. Here’s what it looks like, for me:
> 
> https://www.brinckerhoff.org/tmp/many-windows-1.png
> 
> There are *hundreds* of the little buggers.
> 
> This seems like it’s clearly a Bad Thing. I can’t really say whether it’s a DrR or a Racket thing, though.
> 
> Opinions?
> 
> John
>

**Comment by florence** [comment] 2018-02-01 21:28
I was just about to reply to that thread!

FWIW looking at other people's laptops in my lab this doesn't happen on El Capitan or Sierra, only on High Sierra.

**Comment by jbclements** [comment] 2018-02-01 22:46
> On Feb 1, 2018, at 1:28 PM, Spencer Florence <notifications@github.com> wrote:
> 
> I was just about to reply to that thread!
> 
> FWIW looking at other people's laptops in my lab this doesn't happen on El Capitan or Sierra, only on High Sierra.

Sounds like something that should be fixed :).

John

**Comment by mflatt** [comment] 2018-02-05 20:17
I've upgraded a machine to High Sierra, but I'm not able to replicate the problem.

I see that I'm on 10.13.3. I don't suppose there could be a difference between 10.13.2 and 10.13.3?

**Comment by jbclements** [comment] 2018-02-07 22:44
> On Feb 5, 2018, at 12:17 PM, Matthew Flatt <notifications@github.com> wrote:
> 
> I've upgraded a machine to High Sierra, but I'm not able to replicate the problem.
> 
> I see that I'm on 10.13.3. I don't suppose there could be a difference between 10.13.2 and 10.13.3?

I can still reproduce both of these problems (Spencer’s reported problem, and my GC icon problem) on 10.13.3.

In case this is helpful: I find the three-finger-upward-swipe very useful in observing this problem (both flavors), because it ensures that all windows are non-overlapping, and allows you to see all of the little floating bits left behind by these operations.

John

**Comment by jbclements** [comment] 2018-02-07 22:46
I should also mention that the created windows can be hard to spot, because (in my observations) they’re all overlapped up at the top left corner of the screen.

John

**Comment by mflatt** [comment] 2018-03-28 16:21
I was never able to replicate the problem. Does @Bubba's repair work for others?

**Comment by jbclements** [comment] 2018-03-28 19:04
I had to --clone the gui package to get the new version (I'm guessing it will show up in the package repository some time ... oh! I think it already has).  Either way: yes, I can no longer reproduce either this issue or the one I reported. I believe this issue is now resolved.  Many thanks! 

I'm going to close this, but of course @florence can re-open it if it's still an issue.

**Closed by jbclements** 2018-03-28 19:04 UTC
